### ISSUE TITLE
PSA: `lz4` dependency

### ISSUE THREAD

**Issue by scarlehoff** [conda-forge/eko-feedstock#10]
The `lz4` dependency is needed to run `eko`. However, at the moment is not added as dependency of the package because we would need `lz4-c==1.9.4` which is not available in `conda-forge`: https://anaconda.org/conda-forge/lz4-c

https://github.com/conda-forge/eko-feedstock/blob/84a4a8084e7b0c5ab8809575364b30724abdadde/recipe/meta.yaml#L40

If you want to use eko, you will need to install `lz4` by hand (`conda install lz4` should suffice, also, `lz4-c` is available from the default conda repositories).

**Comment by alecandido** [comment]
> `lz4-c==1.9.4` which is not available in `conda-forge`

This is now available, even though EKO now depends on `lz4 v4` (also available on `conda-forge`).
Could you try to restore the dependency?

**Comment by scarlehoff** [comment]
Fixed in #12
